image: maven:3-openjdk-11

variables:
  MVN_REPO: $CI_PROJECT_DIR/maven-repo

cache:
  paths:
    - $MVN_REPO/

stages:
  - test
  - integration-test

test:
  stage: test
  script:
    - mvn test -B -Dmaven.repo.local=$MVN_REPO

integration-test:
  stage: integration-test
  services:
    - name: docker:dind
      command: ["--tls=false"]
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
  script:
    - mvn verify -B -DskipUnitTests -Dmaven.repo.local=$MVN_REPO
  artifacts:
    paths:
      - target/gitlab-tools.jar
